<a target="_blank" href="https://colab.research.google.com/github/lukebarousse/Int_SQL_Data_Analytics_Course/blob/main/Resources/Blank_SQL_Notebook.ipynb">
  <img src="https://colab.research.google.com/assets/colab-badge.svg" alt="Open In Colab"/>
</a>

# Blank SQL Notebook

#### Import Libraries & Database

The sql extension is already loaded. To reload it, use:
  %reload_ext sql

Connecting and switching to connection 'postgresql://postgres:***@localhost:5432/contoso_100k'

In [94]:
%%sql

SELECT
  p.categoryname AS category,
  AVG(CASE WHEN s.orderdate BETWEEN '2022-01-01' AND'2022-12-31' THEN (s.quantity * s.netprice * s.exchangerate) END) AS avg_net_revenue_2022,
  AVG(CASE WHEN s.orderdate BETWEEN '2023-01-01' AND'2023-12-31' THEN (s.quantity * s.netprice * s.exchangerate) END) AS avg_net_revenue_2023,
  MIN(CASE WHEN s.orderdate BETWEEN '2022-01-01' AND'2022-12-31' THEN (s.quantity * s.netprice * s.exchangerate) END) AS min_net_revenue_2022,
  MIN(CASE WHEN s.orderdate BETWEEN '2023-01-01' AND'2023-12-31' THEN (s.quantity * s.netprice * s.exchangerate) END) AS min_net_revenue_2023,
  MAX(CASE WHEN s.orderdate BETWEEN '2022-01-01' AND'2022-12-31' THEN (s.quantity * s.netprice * s.exchangerate) END) AS max_net_revenue_2022,
  MAX(CASE WHEN s.orderdate BETWEEN '2023-01-01' AND'2023-12-31' THEN (s.quantity * s.netprice * s.exchangerate) END) AS max_net_revenue_2023
FROM
  sales s
LEFT JOIN product p ON s.productkey = p.productkey
GROUP BY
  p.categoryname
ORDER BY
  category;

Running query in 'postgresql://postgres:***@localhost:5432/contoso_100k'

8 rows affected.

,category,avg_net_revenue_2022,avg_net_revenue_2023,min_net_revenue_2022,min_net_revenue_2023,max_net_revenue_2022,max_net_revenue_2023
0,Audio,392.30,425.38,9.31,10.85,3473.36,2730.87
1,Cameras and camcorders,1210.02,1210.96,6.74,5.98,15008.39,13572.00
2,Cell phones,722.20,623.28,2.53,2.28,7692.37,8912.22
3,Computers,1565.62,1292.39,0.83,0.75,38082.66,27611.60
4,Games and Toys,81.29,80.83,2.83,3.49,5202.01,3357.30
5,Home Appliances,1755.36,1886.55,4.04,4.54,31654.55,32915.59
6,"Music, Movies and Audio Books",386.61,334.58,7.29,6.91,5415.19,3804.91
7,TV and Video,1535.61,1687.90,41.30,42.30,30259.41,27503.12